model_list:
  - model_name: gpt-5.2
    litellm_params:
      model: openrouter/openai/gpt-5.2
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: gpt-5.2-direct
    litellm_params:
      model: openai/gpt-5.2-2025-12-11
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-4-5-opus-latest
    litellm_params:
      model: openrouter/anthropic/claude-opus-4.5
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: gemini-3-pro-preview
    litellm_params:
      model: openrouter/google/gemini-3-pro-preview
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: gemini-2.5-pro
    litellm_params:
      model: openrouter/google/gemini-2.5-pro
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: gemini-3-flash-preview
    litellm_params:
      model: openrouter/google/gemini-3-flash-preview
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: gpt-oss-120b
    litellm_params:
      model: openrouter/openai/gpt-oss-120b
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: kimi-k2-thinking
    litellm_params:
      model: openrouter/moonshotai/kimi-k2-thinking
      api_key: os.environ/OPENROUTER_API_KEY

litellm_settings:
  drop_params: true
  modify_params: true
